apiVersion: v1
kind: ServiceAccount
metadata:
  name: collector-poller
  labels:
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: collector-poller
    app.kubernetes.io/name: cardinalhq-otel-collector
