apiVersion: v1
kind: Service
metadata:
  name: collector-gateway-external
  labels:
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: collector-gateway
    app.kubernetes.io/name: cardinalhq-otel-collector
spec:
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
  selector:
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: collector-gateway
    app.kubernetes.io/name: cardinalhq-otel-collector
