apiVersion: v1
kind: Service
metadata:
  name: collector-gateway-interproc
  labels:
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: collector-gateway
    app.kubernetes.io/name: cardinalhq-otel-collector
spec:
  ports:
    - name: chqipc-http
      port: 24318
      targetPort: 24318
      protocol: TCP
  selector:
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: collector-gateway
    app.kubernetes.io/name: cardinalhq-otel-collector
