apiVersion: v1
kind: Service
metadata:
  name: collector-gateway-headless
  labels:
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: collector-gateway
    app.kubernetes.io/name: cardinalhq-otel-collector
spec:
  clusterIP: None
  ports:
    - name: loadbalancer
      port: 14317
      targetPort: 14317
      protocol: TCP
  selector:
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: collector-gateway
    app.kubernetes.io/name: cardinalhq-otel-collector
