apiVersion: v1
kind: ServiceAccount
metadata:
  name: collector-gateway
  labels:
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: collector-gateway
    app.kubernetes.io/name: cardinalhq-otel-collector
