apiVersion: v2
name: lakerunner
description: A Helm chart for LakeRunner - a log and metrics processing platform
type: application
version: "2.5.2"
appVersion: "v1.15.1"
keywords:
  - lakerunner
  - logs
  - metrics
  - traces
  - operations
  - observability
  - grafana
  - agentic
  - mcp
home: https://docs.cardinalhq.io/lakerunner
icon: https://docs.cardinalhq.io/lakerunner_left.png
maintainers:
  - name: Cardinal HQ
    email: support@cardinalhq.com
