apiVersion: v2
name: lakerunner
description: A Helm chart for LakeRunner - a log and metrics processing platform
type: application
version: "2.0.1"
appVersion: "v1.12.3-rc5"
keywords:
  - lakerunner
  - logs
  - metrics
  - traces
  - operations
  - observability
  - grafana
home: https://github.com/cardinalhq/lakerunner
icon: https://docs.cardinalhq.io/lakerunner_left.png
sources:
  - https://github.com/cardinalhq/lakerunner
maintainers:
  - name: Cardinal HQ
    email: support@cardinalhq.com
