apiVersion: v2
name: lakerunner
description: A Helm chart for LakeRunner - a log and metrics processing platform
type: application
version: "1.4.4"
appVersion: "v1.10.5"
keywords:
  - lakerunner
  - logs
  - metrics
  - traces
  - operations
  - observability
  - grafana
home: https://github.com/cardinalhq/lakerunner
icon: https://raw.githubusercontent.com/cardinalhq/lakerunner/main/assets/lakerunner-chip.png
sources:
  - https://github.com/cardinalhq/lakerunner
maintainers:
  - name: Cardinal HQ
    email: support@cardinalhq.com
