# Default values for lakerunner
# This is a YAML-formatted file.

# Global settings
global:
  imagePullSecrets: []
  annotations: {}
  labels: {}
  env: []
  nodeSelector: {}
  tolerations: []
  affinity: {}
  serviceAccount:
    create: true
    name: "lakerunner"
    annotations: {}

# Set the AWS region and credentials for the LakeRunner deployment.
# By default, the credentials are not created, and expected to be in an existing Kubernetes secret
# with the keys `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
#
# This is a limitation in the QueryAPI that we cannot currently pull this in through any other
# means, as the DuckDB driver requires these to be actual keys.
aws:
  # AWS region for the LakeRunner deployment.
  # Required.
  region: "us-east-2"  # AWS region for the deployment

  # Name of the Kubernetes secret that contains the AWS credentials.
  # This secret should contain the keys `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
  # If `aws.create` is set to true, this secret will be created by the Helm chart.
  # If `aws.create` is set to false, this secret must already exist in the Kubernetes cluster.
  # The secret will have the format `<release-name>-aws-credentials`.
  # If you want to use a different name, you can set it here.
  # Required.
  secretName: "aws-credentials"

  # Whether to create the AWS credentials secret. If set to true, the secret will be created
  # with the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY from the values below.
  # If set to false, the secret must already exist in the Kubernetes cluster.
  create: false

  # Only the data query pods need to have the actual credentials injected if
  # credentials are provivided in some other manner, such as using EKS's
  # IAM roles for service accounts (IRSA).  If you are using IRSA, set this to false.
  # Note that regardless of this setting, the credentials will be injected into the
  # data-query pods, and so the secret key and key ID must be set.
  inject: true

  # AWS credentials. If `aws.create` is set to true, these will be created in the
  # Kubernetes secret specified by `aws.secretName`. If `aws.create` is false, these
  # must be set in the Kubernetes secret specified by `aws.secretName`.
  AWS_SECRET_ACCESS_KEY: ""
  AWS_ACCESS_KEY_ID: ""

# Storage profile configuration
# At least one storage profile is required for the LakeRunner to function.
storageProfiles:
  yaml: []
    # - organization_id: dddddddd-aaaa-4ff9-ae8f-365873c552f0
    #   instance_num: 1
    #   collector_name: "kubepi"
    #   cloud_provider: "aws"
    #   region: "us-east-2"
    #   bucket: "datalake-11ndajkhk"
    #   use_path_style: true

# API keys are used to control access to the data lake through the data-api service.
# Each key must be unique, and it associates an API key with an organization ID.
# An example format is shown below.  If you wish to create the secret outside of the
# helm chart, follow this format, set `apiKeys.create` to `false`, and create a Kubernetes secret
# with the content in the secret under a key named `apikeys.yaml`.
apiKeys:
  secretName: "apikeys" # will have the format <release-name>-apikeys once deployed
  create: true
  yaml: []
    # - organization_id: dddddddd-aaaa-4ff9-ae8f-365873c552f0
    #   keys:
    #     - my-api-key-1
    #     - my-api-key-2

# Database configuration
database:
  secretName: "pg-credentials"  # Name of the Kubernetes secret containing database credentials
  create: true  # Whether to create the database credentials secret
  # LRDB (LakeRunner Database) - PostgreSQL
  lrdb:
    # PostgreSQL hostname.  Required.
    host: ""
    # PostgreSQL port.  Default is 5432.  Required.
    port: 5432
    # PostgreSQL database name.  Required.
    name: "lakerunner"
    # PostgreSQL username.  Required.
    username: "lakerunner"
    # PostgreSQL password.  Optional, but recommended.
    password: ""
    # SSL mode for PostgreSQL connection.  Default is "require".
    # Options are "disable", "allow", "prefer", "require", "verify-ca", and "verify-full".
    # See https://www.postgresql.org/docs/current/libpq-ssl.html#LIBPQ-SSL-SSLMODE-STATEMENTS for more details.
    sslMode: "require"

# Setup job configuration (runs before all other services)
# This job is responsible for running database migrations and initial setup tasks.
setup:
  enabled: true
  image:
    repository: public.ecr.aws/cardinalhq.io/lakerunner
    tag: "latest"
    pullPolicy: Always
  resources:
    requests:
      cpu: 1100m
      memory: 250Mi
    limits:
      cpu: 1100m
      memory: 250Mi

# Ingest Logs configuration
ingestLogs:
  enabled: true
  replicas: 2
  image:
    repository: public.ecr.aws/cardinalhq.io/lakerunner
    tag: "latest"
    pullPolicy: Always
  resources:
    requests:
      cpu: 500m
      memory: 200Mi
    limits:
      cpu: 1100m
      memory: 200Mi
  temporaryStorage:
    size: "10Gi"  # Ephemeral storage for ingest logs
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70

# Ingest Metrics configuration
ingestMetrics:
  enabled: true
  replicas: 2
  image:
    repository: public.ecr.aws/cardinalhq.io/lakerunner
    tag: "latest"
    pullPolicy: Always
  resources:
    requests:
      cpu: 1100m
      memory: 500Mi
    limits:
      cpu: 1100m
      memory: 500Mi
  temporaryStorage:
    size: "10Gi"  # Ephemeral storage for ingest logs
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70

# Compact Logs configuration
compactLogs:
  enabled: true
  replicas: 1
  image:
    repository: public.ecr.aws/cardinalhq.io/lakerunner
    tag: "latest"
    pullPolicy: Always
  resources:
    requests:
      cpu: 11000m
      memory: 500Mi
    limits:
      cpu: 1100m
      memory: 500Mi
  temporaryStorage:
    size: "5Gi"  # Ephemeral storage for ingest logs
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70

# Compact Metrics configuration
compactMetrics:
  enabled: true
  replicas: 1
  image:
    repository: public.ecr.aws/cardinalhq.io/lakerunner
    tag: "latest"
    pullPolicy: Always
  resources:
    requests:
      cpu: 2100m
      memory: 1Gi
    limits:
      cpu: 2100m
      memory: 1Gi
  temporaryStorage:
    size: "5Gi"  # Ephemeral storage for ingest logs
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70

# Rollup Metrics configuration
rollupMetrics:
  enabled: true
  replicas: 1
  image:
    repository: public.ecr.aws/cardinalhq.io/lakerunner
    tag: "latest"
    pullPolicy: Always
  resources:
    requests:
      cpu: 1100m
      memory: 1Gi
    limits:
      cpu: 1100m
      memory: 1Gi
  temporaryStorage:
    size: "10Gi"  # Ephemeral storage for ingest logs
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70

# Sweeper configuration
sweeper:
  enabled: true
  replicas: 1
  image:
    repository: public.ecr.aws/cardinalhq.io/lakerunner
    tag: "latest"
    pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 80Mi
    limits:
      cpu: 250m
      memory: 80Mi

# PubSub configuration
pubsub:
  HTTP:
    enabled: false
    replicas: 2 # recommend at least 2
    service:
      type: ClusterIP
    image:
      repository: public.ecr.aws/cardinalhq.io/lakerunner
      tag: "latest"
      pullPolicy: Always
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 200m
        memory: 200Mi
  SQS:
    enabled: true
    replicas: 1
    queueURL: "https://sqs.us-east-2.amazonaws.com/123456789012/my-queue"
    region: "us-east-2" # should match the region of the SQS queue
    roleARN: ""
    image:
      repository: public.ecr.aws/cardinalhq.io/lakerunner
      tag: "latest"
      pullPolicy: Always
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 200m
        memory: 200Mi

# Query API configuration
queryApi:
  enabled: true
  replicas: 1
  minWorkers: 2
  maxWorkers: 4
  service:
    type: ClusterIP
  image:
    repository: public.ecr.aws/cardinalhq.io/lakerunner/query-api
    tag: "latest"
    pullPolicy: Always
  resources:
    requests:
      cpu: 2000m
      memory: 8Gi
    limits:
      cpu: 2000m
      memory: 8gi

# Query Worker configuration
#
# We do not specify a number of replicas here, as the QueryAPI will scale the number of workers
# based on the number of queries being processed.
queryWorker:
  enabled: true
  image:
    repository: public.ecr.aws/cardinalhq.io/lakerunner/query-worker
    tag: "latest"
    pullPolicy: Always
  resources:
    requests:
      cpu: 3500m
      memory: 12Gi
    limits:
      cpu: 3500m
      memory: 12Gi
  service:
    type: ClusterIP
  temporaryStorage:
    size: "10Gi"  # Ephemeral storage for ingest logs
