apiVersion: v2
name: maestro
description: A Helm chart for Maestro - AI agent server with web UI
type: application
version: "0.7.7"
appVersion: "v1.18.8"
keywords:
  - maestro
  - ai
  - agent
  - mcp
home: https://github.com/cardinalhq/conductor
maintainers:
  - name: Cardinal HQ
    email: support@cardinalhq.com
