apiVersion: v2
name: maestro
description: A Helm chart for Maestro - AI agent server with web UI
type: application
version: "0.5.33"
appVersion: "v1.12.3"
keywords:
  - maestro
  - ai
  - agent
  - mcp
home: https://github.com/cardinalhq/conductor
maintainers:
  - name: Cardinal HQ
    email: support@cardinalhq.com
