apiVersion: v2
name: conductor-server
description: A Helm chart for the CardinalHQ Grafana stack - MCP Gateway, Conductor Server, and Maestro Server
type: application
version: "0.1.0"
appVersion: "v0.1.0"
keywords:
  - grafana
  - mcp
  - conductor
  - maestro
home: https://github.com/cardinalhq/charts
maintainers:
  - name: Cardinal HQ
    email: support@cardinalhq.com
