apiVersion: v1
kind: ServiceAccount
metadata:
  name: collector-agent
  labels:
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: collector-agent
    app.kubernetes.io/name: cardinalhq-otel-collector
