apiVersion: v1
kind: Service
metadata:
  name: collector-agent
  labels:
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: collector-agent
    app.kubernetes.io/name: cardinalhq-otel-collector
spec:
  internalTrafficPolicy: Local
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
  selector:
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: collector-agent
    app.kubernetes.io/name: cardinalhq-otel-collector
