# Default values for loki-mcp
# This is a YAML-formatted file.

# Image configuration
image:
  repository: public.ecr.aws/cardinalhq.io/loki-mcp
  tag: ""
  pullPolicy: IfNotPresent

# Image pull secrets for private registries
imagePullSecrets: []

# Service configuration
service:
  type: ClusterIP
  port: 8080

# Loki configuration
# REQUIRED: You must provide the Loki server address
loki:
  # REQUIRED: Loki server address (e.g., "loki.monitoring:3100")
  address: ""
  # Whether to use HTTPS for Loki connections
  useHttps: false

# CardinalHQ configuration
# REQUIRED: You must provide a CardinalHQ API key
cardinal:
  # REQUIRED: CardinalHQ API key for fetching OpenAI and Anthropic keys
  apiKey: ""
  secret:
    name: "cardinal-api-key"
    create: true

# Lakerunner configuration (optional)
lakerunner:
  # Lakerunner API host for query validation (optional)
  apiHost: ""

# Resource limits and requests
resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi
