{{- if .Values.database.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "maestro.databaseSecretName" . }}
  labels:
    {{- include "maestro.labels" . | nindent 4 }}
  {{ include "maestro.annotations" . | nindent 2 }}
type: Opaque
data:
  {{ .Values.database.passwordKey }}: {{ .Values.database.password | b64enc }}
{{- end }}
