{{- if .Values.uiWeb.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "maestro.fullname" . }}-ui-web
  labels:
    {{- include "maestro.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui-web
  {{ include "maestro.annotations" . | nindent 2 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.uiWeb.port }}
      targetPort: http
      name: http
  selector:
    {{- include "maestro.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui-web
{{- end }}
