{{- if and .Values.auth.token (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flamethrower.fullname" . }}-auth
  labels: {{- include "flamethrower.labels" . | nindent 4 }}
type: Opaque
stringData:
  FLAMETHROWER_AUTH_TOKEN: {{ .Values.auth.token | quote }}
{{- end }}
