{{- if and .Values.tokens.key (not .Values.tokens.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flamethrower.fullname" . }}-tokens
  labels: {{- include "flamethrower.labels" . | nindent 4 }}
type: Opaque
stringData:
  FLAMETHROWER_TOKEN_KEY: {{ .Values.tokens.key | quote }}
{{- end }}
