{{- if and (eq .Values.auth.mode "static") .Values.auth.staticCreds }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.secretName }}
  labels: {{- include "flamethrower.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.auth.staticCreds.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.auth.staticCreds.secretAccessKey | quote }}
{{- end }}
