apiVersion: v1
kind: Service
metadata:
  name: {{ include "flamethrower.fullname" . }}
  labels: {{- include "flamethrower.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "flamethrower.selectorLabels" . | nindent 4 }}
  ports:
    - name: control
      port: {{ .Values.service.port }}
      targetPort: control
      protocol: TCP
