{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels: {{- include "flamethrower.labels" . | nindent 4 }}
  annotations:
    {{- if eq .Values.auth.mode "irsa" }}
    eks.amazonaws.com/role-arn: {{ .Values.auth.roleArn | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
