{{- if .Values.loki.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lgtm-mcp.loki.fullname" . }}
  labels:
    {{- include "lgtm-mcp.loki.labels" . | nindent 4 }}
spec:
  type: {{ .Values.loki.service.type }}
  ports:
    - port: {{ .Values.loki.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lgtm-mcp.loki.selectorLabels" . | nindent 4 }}
{{- end }}
