{{- if .Values.tempo.enabled }}
{{- include "lgtm-mcp.validateValues" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lgtm-mcp.tempo.fullname" . }}
  labels:
    {{- include "lgtm-mcp.tempo.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "lgtm-mcp.tempo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lgtm-mcp.tempo.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.tempo.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
      containers:
      - name: tempo-mcp
        image: {{ include "lgtm-mcp.tempo.image" . }}
        imagePullPolicy: {{ .Values.tempo.image.pullPolicy }}
        command: ["/app/tempo-mcp"]
        args:
          - "--http"
          - "--host=0.0.0.0"
          - "--port=8080"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        envFrom:
        - secretRef:
            name: {{ include "lgtm-mcp.tempo.fullname" . }}-config
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        resources:
          {{- toYaml .Values.tempo.resources | nindent 10 }}
        volumeMounts:
        - name: tenants-config
          mountPath: /app/config/tenants.yaml
          subPath: tenants.yaml
          readOnly: true
      volumes:
      - name: tenants-config
        configMap:
          name: {{ include "lgtm-mcp.tempo.fullname" . }}-tenants
{{- end }}
