apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "lakerunner.fullname" . }}-apikeys
  labels:
    {{- include "lakerunner.labels" . | nindent 4 }}
data:
  apikeys.yaml: {{ .Values.apiKeys.yaml | toYaml | b64enc | quote }}
