{{- if .Values.aws.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lakerunner.fullname" . }}-{{ .Values.aws.secretName }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID:     {{ .Values.aws.accessKeyId     | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey | b64enc }}
{{- end }}
