{{- if and (eq .Values.cloudProvider.provider "aws") .Values.cloudProvider.aws.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lakerunner.cloudProviderSecretName" . }}
  labels:
    {{- include "lakerunner.labels" . | nindent 4 }}
  {{ include "lakerunner.annotations" . | nindent 2 }}
data:
  {{- if and .Values.cloudProvider.aws.accessKeyId .Values.cloudProvider.aws.secretAccessKey }}
  AWS_ACCESS_KEY_ID:     {{ .Values.cloudProvider.aws.accessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.cloudProvider.aws.secretAccessKey | b64enc }}
  {{- end }}
{{- end }}
