{{- if and (eq .Values.cloudProvider.provider "azure") .Values.cloudProvider.azure.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lakerunner.cloudProviderSecretName" . }}
  labels:
    {{- include "lakerunner.labels" . | nindent 4 }}
  {{ include "lakerunner.annotations" . | nindent 2 }}
data:
  {{- $authType := .Values.cloudProvider.azure.authType | default "service_principal" }}
  
  {{- if eq $authType "service_principal" }}
  {{- if and .Values.cloudProvider.azure.clientId .Values.cloudProvider.azure.clientSecret .Values.cloudProvider.azure.tenantId }}
  AZURE_CLIENT_ID:     {{ .Values.cloudProvider.azure.clientId | b64enc }}
  AZURE_CLIENT_SECRET: {{ .Values.cloudProvider.azure.clientSecret | b64enc }}
  AZURE_TENANT_ID:     {{ .Values.cloudProvider.azure.tenantId | b64enc }}
  {{- end }}
  
  {{- else if eq $authType "user_managed_identity" }}
  {{- if .Values.cloudProvider.azure.clientId }}
  AZURE_CLIENT_ID:     {{ .Values.cloudProvider.azure.clientId | b64enc }}
  {{- end }}
  
  {{- else if eq $authType "workload_identity" }}
  {{- if and .Values.cloudProvider.azure.clientId .Values.cloudProvider.azure.tenantId }}
  AZURE_CLIENT_ID:     {{ .Values.cloudProvider.azure.clientId | b64enc }}
  AZURE_TENANT_ID:     {{ .Values.cloudProvider.azure.tenantId | b64enc }}
  AZURE_FEDERATED_TOKEN_FILE: {{ .Values.cloudProvider.azure.federatedTokenFile | default "/var/run/secrets/azure/tokens/azure-identity-token" | b64enc }}
  {{- end }}
  
  {{- else if eq $authType "connection_string" }}
  {{- if .Values.cloudProvider.azure.connectionString }}
  AZURE_STORAGE_CONNECTION_STRING: {{ .Values.cloudProvider.azure.connectionString | b64enc }}
  {{- end }}
  
  {{- else if eq $authType "system_managed_identity" }}
  # No credentials needed for system managed identity
  {{- end }}
{{- end }}