{{- if .Values.global.cardinal.apiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lakerunner.fullname" . }}-cardinal-api-key
  labels:
    {{- include "lakerunner.labels" . | nindent 4 }}
type: Opaque
data:
  # raw API key
  CARDINAL_API_KEY: {{ .Values.global.cardinal.apiKey | b64enc }}
  # pre-formatted OTLP header string
  CARDINAL_API_HEADER: {{ printf "x-cardinalhq-api-key=%s" .Values.global.cardinal.apiKey | b64enc }}
{{- end }}
