{{- if and .Values.global.cardinal.apiKey .Values.storageProfiles.yaml .Values.collector.enabled }}
{{- $storageProfile := index .Values.storageProfiles.yaml 0 }}
{{- if and $storageProfile.cloud_provider $storageProfile.bucket $storageProfile.region $storageProfile.collector_name $storageProfile.organization_id $storageProfile.collector_name }}
---
apiVersion: collector.cardinalhq.io/v1alpha1
kind: Collector
metadata:
  name: {{ include "lakerunner.fullname" . }}-collector
  labels:
    {{- include "lakerunner.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
    {{- if and (eq .Values.cloudProvider.provider "azure") (eq .Values.cloudProvider.azure.authType "workload_identity") }}
    azure.workload.identity/use: "true"
    {{- end }}
    lakerunner.cardinalhq.io/bucket: {{ $storageProfile.bucket }}
    lakerunner.cardinalhq.io/region: {{ $storageProfile.region }}
    lakerunner.cardinalhq.io/cloud-provider: {{ $storageProfile.cloud_provider }}
    {{- if .Values.collector.labels }}
    {{- toYaml .Values.collector.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.collector.annotations }}
    {{- toYaml .Values.collector.annotations | nindent 4 }}
    {{- end }}
spec:
  environment: {{ .Values.global.cardinal.env }}
  collectorStyle: gateway
  collectorName: {{ $storageProfile.collector_name }}
  apiKeySecretRef: {{ include "lakerunner.fullname" . }}-cardinal-api-key

  features:
{{- if eq $storageProfile.cloud_provider "azure" }}
    azureblobexporter:
      container: {{ $storageProfile.bucket }}
      {{- if $storageProfile.endpoint }}
      endpoint: {{ $storageProfile.endpoint }}
      {{- end }}
      organizationId: {{ $storageProfile.organization_id }}
      collectorName: {{ $storageProfile.collector_name }}
      auth_type: {{ .Values.cloudProvider.azure.authType }}
{{- else }}
    awss3:
      provider: {{ $storageProfile.cloud_provider }}
      bucket: {{ $storageProfile.bucket }}
      region: {{ $storageProfile.region }}
      organizationId: {{ $storageProfile.organization_id }}
      collectorName: {{ $storageProfile.collector_name }}
{{- end }}

{{- if eq (include "lakerunner.injectCloudProviderCredentials" .) "true" }}
  envFrom:
    - secretRef:
        name: {{ include "lakerunner.cloudProviderSecretName" . }}
{{- end }}

  env:
    {{- if eq .Values.cloudProvider.provider "azure" }}
    {{- $authType := .Values.cloudProvider.azure.authType | default "service_principal" }}
    - name: AZURE_AUTH_TYPE
      value: {{ $authType | quote }}
    {{- end }}
    {{- if .Values.collector.env }}
    {{- toYaml .Values.collector.env | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
