{{- if .Values.grafana.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lakerunner.fullname" . }}-grafana
  labels:
    {{- include "lakerunner.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
  {{ include "lakerunner.annotations" . | nindent 2 }}
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lakerunner.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
{{- end }} 