{{- if .Values.ingestMetrics.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lakerunner.fullname" . }}-ingest-metrics
  labels:
    {{- include "lakerunner.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingest-metrics
  {{ include "lakerunner.annotations" . | nindent 2 }}
spec:
  {{- if not .Values.ingestMetrics.autoscaling.enabled }}
  replicas: {{ .Values.ingestMetrics.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "lakerunner.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ingest-metrics
  template:
    metadata:
      labels:
        {{- include "lakerunner.labels" . | nindent 8 }}
        app.kubernetes.io/component: ingest-metrics
      {{- include "lakerunner.annotations" . | nindent 6 }}
    spec:
      serviceAccountName: {{ include "lakerunner.serviceAccountName" . }}
      terminationGracePeriodSeconds: 120
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
      {{- include "lakerunner.imagePullSecrets" . | nindent 2 }}
      containers:
      - name: ingest-metrics
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        image: "{{ .Values.ingestMetrics.image.repository }}:{{ .Values.ingestMetrics.image.tag }}"
        imagePullPolicy: {{ .Values.ingestMetrics.image.pullPolicy }}
      {{- include "lakerunner.sched.nodeSelector" (list .Values.global.nodeSelector .Values.ingestMetrics.nodeSelector) | nindent 6 }}
      {{- include "lakerunner.sched.tolerations"  (list .Values.global.tolerations  .Values.ingestMetrics.tolerations)  | nindent 6 }}
      {{- include "lakerunner.sched.affinity"     (list .Values.global.affinity     .Values.ingestMetrics.affinity)     | nindent 6 }}
        command: ["/app/bin/lakerunner"]
        args: ["ingest-metrics"]
        env:
          - name: TMPDIR
            value: /scratch
          {{- include "lakerunner.injectEnv" (list . .Values.ingestMetrics) | nindent 8 }}
        {{- if .Values.aws.inject }}
        envFrom:
        - secretRef:
            name: {{ include "lakerunner.awsSecretName" . }}
        {{- end }}
        resources:
          {{- toYaml .Values.ingestMetrics.resources | nindent 10 }}
        volumeMounts:
        {{- if eq .Values.storageProfiles.source "config" }}
        - name: storage-profiles
          mountPath: /app/config
          readOnly: true
        {{- end }}
        - name: scratch
          mountPath: /scratch
      volumes:
      - name: scratch
        emptyDir:
          sizeLimit: {{ .Values.compactLogs.temporaryStorage.size | quote }}
      {{- if eq .Values.storageProfiles.source "config" }}
      - name: storage-profiles
        configMap:
          name: {{ include "lakerunner.storageProfilesConfigmapName" . }}
      {{- end }}
      {{- with .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
