{{- if .Values.internalServiceKeys.create -}}
{{- $secretName := include "lakerunner.intkeySecretName" . -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "lakerunner.labels" . | nindent 4 }}
  {{ include "lakerunner.annotations" . | nindent 2 }}
data:
  {{- if $existing }}
  internal-service-keys: {{ index $existing.data "internal-service-keys" }}
  {{- else }}
  internal-service-keys: {{ randAlphaNum 64 | b64enc }}
  {{- end }}
{{- end }}
