{{- if eq .Values.global.autoscaling.mode "keda" -}}
{{- if not .Values.database.lrdb.host -}}
{{- fail "database.lrdb.host is required when using KEDA scaling mode" -}}
{{- end -}}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ include "lakerunner.fullname" . }}-keda-auth
  labels:
    {{- include "lakerunner.labels" . | nindent 4 }}
  {{ include "lakerunner.annotations" . | nindent 2 }}
spec:
  secretTargetRef:
  - parameter: password
    name: {{ include "lakerunner.databaseSecretName" . }}
    key: {{ .Values.database.passwordKey }}
{{- end }}