{{- if and .Values.license.create .Values.license.data -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "lakerunner.licenseSecretName" . }}
  labels:
    {{- include "lakerunner.labels" . | nindent 4 }}
  {{ include "lakerunner.annotations" . | nindent 2 }}
data:
  license.json: {{ .Values.license.data | b64enc | quote }}
{{- end }}
