{{- if and .Values.perch.enabled .Values.perch.maestro.apiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lakerunner.fullname" . }}-perch
  labels:
    {{- include "lakerunner.labels" . | nindent 4 }}
    app.kubernetes.io/component: perch
  {{ include "lakerunner.annotations" . | nindent 2 }}
type: Opaque
data:
  maestro-api-key: {{ .Values.perch.maestro.apiKey | b64enc | quote }}
{{- end }}
