{{- if .Values.database.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lakerunner.databaseSecretName" . }}
type: Opaque
data:
  LRDB_PASSWORD: {{ .Values.database.lrdb.password | b64enc }}
{{- end }}
