{{- if .Values.pubsub.Azure.enabled -}}
{{- if not .Values.pubsub.Azure.storageAccount -}}
{{- fail "pubsub.Azure.storageAccount is required when pubsub.Azure.enabled is true" -}}
{{- end -}}
{{- if not .Values.pubsub.Azure.queueName -}}
{{- fail "pubsub.Azure.queueName is required when pubsub.Azure.enabled is true" -}}
{{- end -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lakerunner.fullname" . }}-pubsub-azure
  labels:
    {{- include "lakerunner.labels" . | nindent 4 }}
    app.kubernetes.io/component: pubsub-azure
  {{ include "lakerunner.annotations" . | nindent 2 }}
spec:
  replicas: {{ .Values.pubsub.Azure.replicas }}
  selector:
    matchLabels:
      {{- include "lakerunner.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: pubsub-azure
  template:
    metadata:
      labels:
        {{- include "lakerunner.labels" . | nindent 8 }}
        app.kubernetes.io/component: pubsub-azure
        {{- if eq .Values.cloudProvider.azure.authType "workload_identity" }}
        azure.workload.identity/use: "true"
        {{- end }}
      {{- include "lakerunner.annotations" . | nindent 6 }}
    spec:
      serviceAccountName: {{ include "lakerunner.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.pubsub.Azure.terminationGracePeriodSeconds }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
      {{- include "lakerunner.imagePullSecrets" . | nindent 6 }}
      containers:
      - name: pubsub
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        image: {{ include "lakerunner.image" (list .Values.pubsub.Azure.image .) }}
        imagePullPolicy: {{ .Values.pubsub.Azure.image.pullPolicy | default .Values.global.image.pullPolicy }}
        command: ["/app/bin/lakerunner"]
        args: ["pubsub", "azure"]
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: OTEL_SERVICE_NAME
            value: {{ include "lakerunner.fullname" . }}-pubsub-azure
          - name: AZURE_STORAGE_ACCOUNT
            value: {{ .Values.pubsub.Azure.storageAccount | quote }}
          - name: AZURE_QUEUE_NAME
            value: {{ .Values.pubsub.Azure.queueName | quote }}
          {{- include "lakerunner.injectEnv" (list . .Values.pubsub.Azure) | nindent 8 }}
          {{- include "lakerunner.cardinalTelemetryEnv" . | nindent 10 }}
          {{- include "lakerunner.kafkaEnv" . | nindent 10 }}
        {{- if eq (include "lakerunner.injectCloudProviderCredentials" .) "true" }}
        envFrom:
          - secretRef:
              name: {{ include "lakerunner.cloudProviderSecretName" . }}
        {{- end }}
        resources:
          {{- toYaml .Values.pubsub.Azure.resources | nindent 10 }}
        {{- if eq .Values.storageProfiles.source "config" }}
        volumeMounts:
        - name: storage-profiles
          mountPath: /app/config/storage_profiles.yaml
          subPath: storage_profiles.yaml
          readOnly: true
        {{- end }}
      {{- include "lakerunner.sched.nodeSelector" (list .Values.global.nodeSelector .Values.pubsub.Azure.nodeSelector) | nindent 6 }}
      {{- include "lakerunner.sched.tolerations"  (list .Values.global.tolerations  .Values.pubsub.Azure.tolerations)  | nindent 6 }}
      {{- include "lakerunner.sched.affinity"     (list .Values.global.affinity     .Values.pubsub.Azure.affinity)     | nindent 6 }}
      {{- if eq .Values.storageProfiles.source "config" }}
      volumes:
      - name: storage-profiles
        configMap:
          name: {{ include "lakerunner.storageProfilesConfigmapName" . }}
      {{- end }}
{{- end }}