{{- if .Values.pubsub.HTTP.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lakerunner.fullname" . }}-pubsub-http
  labels:
    {{- include "lakerunner.labels" . | nindent 4 }}
    app.kubernetes.io/component: pubsub-http
  {{ include "lakerunner.annotations" . | nindent 2 }}
spec:
  replicas: {{ .Values.pubsub.HTTP.replicas }}
  selector:
    matchLabels:
      {{- include "lakerunner.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: pubsub-http
  template:
    metadata:
      labels:
        {{- include "lakerunner.labels" . | nindent 8 }}
        app.kubernetes.io/component: pubsub-http
      {{- include "lakerunner.annotations" . | nindent 6 }}
    spec:
      serviceAccountName: {{ include "lakerunner.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.pubsub.HTTP.terminationGracePeriodSeconds }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
      {{- include "lakerunner.imagePullSecrets" . | nindent 6 }}
      containers:
      - name: pubsub
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        image: {{ include "lakerunner.image" (list .Values.pubsub.HTTP.image .) }}
        imagePullPolicy: {{ .Values.pubsub.HTTP.image.pullPolicy | default .Values.global.image.pullPolicy }}
        command: ["/app/bin/lakerunner"]
        args: ["pubsub", "http"]
        ports:
        - containerPort: 8080
          name: http
        env:
          - name: OTEL_SERVICE_NAME
            value: {{ include "lakerunner.fullname" . }}-pubsub-http
          {{- include "lakerunner.injectEnv" (list . .Values.pubsub.HTTP) | nindent 8 }}
        resources:
          {{- toYaml .Values.pubsub.HTTP.resources | nindent 10 }}
        {{- if eq .Values.storageProfiles.source "config" }}
        volumeMounts:
        - name: storage-profiles
          mountPath: /app/config/storage_profiles.yaml
          subPath: storage_profiles.yaml
          readOnly: true
        {{- end }}
      {{- include "lakerunner.sched.nodeSelector" (list .Values.global.nodeSelector .Values.pubsub.HTTP.nodeSelector) | nindent 6 }}
      {{- include "lakerunner.sched.tolerations"  (list .Values.global.tolerations  .Values.pubsub.HTTP.tolerations)  | nindent 6 }}
      {{- include "lakerunner.sched.affinity"     (list .Values.global.affinity     .Values.pubsub.HTTP.affinity)     | nindent 6 }}
      {{- if eq .Values.storageProfiles.source "config" }}
      volumes:
      - name: storage-profiles
        configMap:
          name: {{ include "lakerunner.storageProfilesConfigmapName" . }}
      {{- end }}
{{- end }}
