{{- if .Values.queryApi.enabled -}}
{{- if or (not .Values.aws.region) (eq .Values.aws.region "") (eq .Values.aws.region "CHANGEME") (eq .Values.aws.region "us-test-1") -}}
{{- fail (printf "aws.region must be set to a valid AWS region when queryApi is enabled (current value: %q)" .Values.aws.region) -}}
{{- end -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "lakerunner.fullname" . }}-query-api
  labels:
    {{- include "lakerunner.labels" . | nindent 4 }}
    app.kubernetes.io/component: query-api
    lakerunner.cardinalhq.io/component: query-api
  {{ include "lakerunner.annotations" . | nindent 2 }}
spec:
  replicas: {{ .Values.queryApi.replicas }}
  serviceName: {{ include "lakerunner.fullname" . }}-query-api
  selector:
    matchLabels:
      {{- include "lakerunner.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: query-api
  template:
    metadata:
      labels:
        {{- include "lakerunner.labels" . | nindent 8 }}
        app.kubernetes.io/component: query-api
      {{- include "lakerunner.annotations" . | nindent 6 }}
    spec:
      serviceAccountName: {{ include "lakerunner.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.queryApi.terminationGracePeriodSeconds }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
      {{- include "lakerunner.imagePullSecrets" . | nindent 6 }}
      {{- include "lakerunner.sched.nodeSelector" (list .Values.global.nodeSelector .Values.queryApi.nodeSelector) | nindent 6 }}
      {{- include "lakerunner.sched.tolerations"  (list .Values.global.tolerations  .Values.queryApi.tolerations)  | nindent 6 }}
      {{- include "lakerunner.sched.affinity"     (list .Values.global.affinity     .Values.queryApi.affinity)     | nindent 6 }}
      containers:
      - name: query-api
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        image: {{ include "lakerunner.image" (list .Values.queryApi.image .) }}
        imagePullPolicy: {{ .Values.queryApi.image.pullPolicy | default .Values.global.image.pullPolicy }}
        ports:
        - containerPort: 7101
          name: http
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: OTEL_SERVICE_NAME
            value: {{ include "lakerunner.fullname" . }}-query-api
          - name: METRIC_PREFIX
            value: {{ include "lakerunner.fullname" . }}-query-api
          - name: HOME
            value: "/tmp"
          - name: NUM_MIN_QUERY_WORKERS
            value: "{{ .Values.queryApi.minWorkers }}"
          - name: NUM_MAX_QUERY_WORKERS
            value: "{{ .Values.queryApi.maxWorkers }}"
          - name: SPRING_PROFILES_ACTIVE
            value: aws
          - name: AWS_REGION
            value: {{ .Values.aws.region | quote }}
          {{- if eq .Values.apiKeys.source "config" }}
          - name: API_KEYS_FILE
            value: /app/config/apikeys.yaml
          {{- end }}
          - name: TOKEN_HMAC256_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "lakerunner.tokenSecretName" . }}
                key: TOKEN
          - name: EXECUTION_ENVIRONMENT
            value: "kubernetes"
          - name: QUERY_STACK
            value: local
          {{- include "lakerunner.injectEnv" (list . .Values.queryApi) | nindent 8 }}
        envFrom:
          - secretRef:
              name: {{ include "lakerunner.awsSecretName" . }}
        resources:
          {{- toYaml .Values.queryApi.resources | nindent 10 }}
        {{- if or (eq .Values.storageProfiles.source "config") (eq .Values.apiKeys.source "config") }}
        volumeMounts:
        {{- end }}
        {{- if eq .Values.storageProfiles.source "config" }}
        - name: storage-profiles
          mountPath: /app/config/storage_profiles.yaml
          subPath: storage_profiles.yaml
          readOnly: true
        {{- end }}
        {{- if eq .Values.apiKeys.source "config" }}
        - name: apikeys
          mountPath: /app/config/apikeys.yaml
          subPath: apikeys.yaml
          readOnly: true
        {{- end }}
      {{- if or (eq .Values.storageProfiles.source "config") (eq .Values.apiKeys.source "config") }}
      volumes:
      {{- end }}
      {{- if eq .Values.storageProfiles.source "config" }}
      - name: storage-profiles
        configMap:
          name: {{ include "lakerunner.storageProfilesConfigmapName" . }}
      {{- end }}
      {{- if eq .Values.apiKeys.source "config" }}
      - name: apikeys
        secret:
          secretName: {{ include "lakerunner.apiKeysSecretName" . }}
      {{- end }}
{{- end }}
