{{- if .Values.queryApi.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "lakerunner.fullname" . }}-query-api
  labels:
    {{- include "lakerunner.labels" . | nindent 4 }}
    app.kubernetes.io/component: query-api
  annotations:
    {{- toYaml .Values.global.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.queryApi.replicas }}
  serviceName: {{ include "lakerunner.fullname" . }}-query-api
  selector:
    matchLabels:
      {{- include "lakerunner.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: query-api
  template:
    metadata:
      labels:
        {{- include "lakerunner.labels" . | nindent 8 }}
        app.kubernetes.io/component: query-api
    spec:
      serviceAccountName: {{ include "lakerunner.serviceAccountName" . }}
      terminationGracePeriodSeconds: 120
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
      {{- include "lakerunner.imagePullSecrets" . | nindent 2 }}
      containers:
      - name: query-api
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        image: "{{ .Values.queryApi.image.repository }}:{{ .Values.queryApi.image.tag }}"
        imagePullPolicy: {{ .Values.queryApi.image.pullPolicy }}
        ports:
        - containerPort: 7101
          name: http
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HOME
            value: "/tmp"
          - name: NUM_MIN_QUERY_WORKERS
            value: "{{ .Values.queryApi.minWorkers }}"
          - name: NUM_MAX_QUERY_WORKERS
            value: "{{ .Values.queryApi.maxWorkers }}"
          - name: SPRING_PROFILES_ACTIVE
            value: aws
          - name: AWS_REGION
            value: {{ .Values.aws.region | quote }}
          {{- include "lakerunner.commonEnv" . | nindent 10 }}
        envFrom:
          - secretRef:
              name: {{ include "lakerunner.fullname" . }}-aws-credentials
        resources:
          {{- toYaml .Values.queryApi.resources | nindent 10 }}
        volumeMounts:
        - name: storage-profiles
          mountPath: /app/config/storage_profiles.yaml
          subPath: storage_profiles.yaml
          readOnly: true
        - name: apikeys
          mountPath: /app/config/apikeys.yaml
          subPath: apikeys.yaml
          readOnly: true
      volumes:
      - name: storage-profiles
        configMap:
          name: {{ include "lakerunner.fullname" . }}-storage-profiles
      - name: apikeys
        secret:
          secretName: {{ include "lakerunner.fullname" . }}-apikeys
      {{- with .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
