{{- if .Values.queryWorker.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lakerunner.fullname" . }}-query-worker
  labels:
    {{- include "lakerunner.labels" . | nindent 4 }}
    app.kubernetes.io/component: query-worker
  {{ include "lakerunner.annotations" . | nindent 2 }}
spec:
  type: {{ .Values.queryWorker.service.type }}
  ports:
    - port: 7101
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lakerunner.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: query-worker
{{- end }}
