apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "lakerunner.fullname" . }}-scaler
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["query-worker"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "lakerunner.fullname" . }}-scaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name:  {{ include "lakerunner.fullname" . }}-scaler
subjects:
  - kind: ServiceAccount
    name:  {{ include "lakerunner.serviceAccountName" . }}
    namespace: {{ include "lakerunner.namespace" . }}
