{{- if .Values.rollupMetrics.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lakerunner.fullname" . }}-rollup-metrics
  labels:
    {{- include "lakerunner.labels" . | nindent 4 }}
    app.kubernetes.io/component: rollup-metrics
  {{ include "lakerunner.annotations" . | nindent 2 }}
spec:
  {{- $scalingMode := include "lakerunner.autoscalingMode" (list .Values.rollupMetrics.autoscaling .) }}
  {{- if eq $scalingMode "disabled" }}
  replicas: {{ .Values.rollupMetrics.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "lakerunner.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: rollup-metrics
  template:
    metadata:
      labels:
        {{- include "lakerunner.labels" . | nindent 8 }}
        app.kubernetes.io/component: rollup-metrics
      {{- include "lakerunner.annotations" . | nindent 6 }}
    spec:
      serviceAccountName: {{ include "lakerunner.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.rollupMetrics.terminationGracePeriodSeconds }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
      {{- include "lakerunner.imagePullSecrets" . | nindent 6 }}
        {{- include "lakerunner.sched.nodeSelector" (list .Values.global.nodeSelector .Values.rollupMetrics.nodeSelector) | nindent 6 }}
        {{- include "lakerunner.sched.tolerations"  (list .Values.global.tolerations  .Values.rollupMetrics.tolerations)  | nindent 6 }}
        {{- include "lakerunner.sched.affinity"     (list .Values.global.affinity     .Values.rollupMetrics.affinity)     | nindent 6 }}
      containers:
      - name: rollup-metrics
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        image: {{ include "lakerunner.image" (list .Values.rollupMetrics.image .) }}
        imagePullPolicy: {{ .Values.rollupMetrics.image.pullPolicy | default .Values.global.image.pullPolicy }}
        command: ["/app/bin/lakerunner"]
        args: ["rollup-metrics"]
        env:
          - name: OTEL_SERVICE_NAME
            value: {{ include "lakerunner.fullname" . }}-rollup-metrics
          - name: TMPDIR
            value: /scratch
          {{- include "lakerunner.injectEnv" (list . .Values.rollupMetrics) | nindent 8 }}
        {{- if .Values.aws.inject }}
        envFrom:
          - secretRef:
              name: {{ include "lakerunner.awsSecretName" . }}
        {{- end }}
        resources:
          {{- toYaml .Values.rollupMetrics.resources | nindent 10 }}
        volumeMounts:
        {{- if eq .Values.storageProfiles.source "config" }}
        - name: storage-profiles
          mountPath: /app/config/storage_profiles.yaml
          subPath: storage_profiles.yaml
          readOnly: true
        {{- end }}
        - name: scratch
          mountPath: /scratch
      volumes:
      - name: scratch
        emptyDir:
          sizeLimit: {{ .Values.compactLogs.temporaryStorage.size | quote }}
      {{- if eq .Values.storageProfiles.source "config" }}
      - name: storage-profiles
        configMap:
          name: {{ include "lakerunner.storageProfilesConfigmapName" . }}
      {{- end }}
{{- end }}
