apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lakerunner.storageProfilesConfigmapName" . }}
  labels:
    {{- include "lakerunner.labels" . | nindent 4 }}
data:
  storage_profiles.yaml: |
{{ .Values.storageProfiles.yaml | toYaml | indent 6 }}
