{{- if .Values.sweeper.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lakerunner.fullname" . }}-sweeper
  labels:
    {{- include "lakerunner.labels" . | nindent 4 }}
    app.kubernetes.io/component: sweeper
  {{ include "lakerunner.annotations" . | nindent 2}}
spec:
  replicas: {{ .Values.sweeper.replicas }}
  selector:
    matchLabels:
      {{- include "lakerunner.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: sweeper
  template:
    metadata:
      labels:
        {{- include "lakerunner.labels" . | nindent 8 }}
        app.kubernetes.io/component: sweeper
      {{- include "lakerunner.annotations" . | nindent 6 }}
    spec:
      serviceAccountName: {{ include "lakerunner.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.sweeper.terminationGracePeriodSeconds }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
      {{- include "lakerunner.imagePullSecrets" . | nindent 6 }}
      {{- include "lakerunner.sched.nodeSelector" (list .Values.global.nodeSelector .Values.sweeper.nodeSelector) | nindent 6 }}
      {{- include "lakerunner.sched.tolerations"  (list .Values.global.tolerations  .Values.sweeper.tolerations)  | nindent 6 }}
      {{- include "lakerunner.sched.affinity"     (list .Values.global.affinity     .Values.sweeper.affinity)     | nindent 6 }}
      containers:
      - name: sweeper
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        image: {{ include "lakerunner.image" (list .Values.sweeper.image .) }}
        imagePullPolicy: {{ .Values.sweeper.image.pullPolicy | default .Values.global.image.pullPolicy }}
        command: ["/app/bin/lakerunner"]
        args: ["sweeper"]
        env:
          - name: OTEL_SERVICE_NAME
            value: {{ include "lakerunner.fullname" . }}-sweeper
          - name: TMPDIR
            value: /scratch
          {{- include "lakerunner.injectEnv" (list . .Values.sweeper) | nindent 8 }}
        {{- if .Values.aws.inject }}
        envFrom:
        - secretRef:
            name: {{ include "lakerunner.awsSecretName" . }}
        {{- end }}
        resources:
          {{- toYaml .Values.sweeper.resources | nindent 10 }}
        {{- if eq .Values.storageProfiles.source "config" }}
        volumeMounts:
        - name: storage-profiles
          mountPath: /app/config/storage_profiles.yaml
          subPath: storage_profiles.yaml
          readOnly: true
        {{- end }}
      {{- if eq .Values.storageProfiles.source "config" }}
      volumes:
      - name: storage-profiles
        configMap:
          name: {{ include "lakerunner.storageProfilesConfigmapName" . }}
      {{- end }}
{{- end }}
