{{- if .Values.mcpGateway.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "conductor-server.mcpGateway.secretName" . }}
  labels:
    {{- include "conductor-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp-gateway
  {{- include "conductor-server.annotations" . | nindent 2 }}
type: Opaque
data:
  {{- range $key, $value := .Values.mcpGateway.secrets.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
---
{{- end }}
{{- if .Values.conductorServer.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "conductor-server.conductorServer.secretName" . }}
  labels:
    {{- include "conductor-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: conductor-server
  {{- include "conductor-server.annotations" . | nindent 2 }}
type: Opaque
data:
  {{- range $key, $value := .Values.conductorServer.secrets.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
---
{{- end }}
{{- if .Values.conductorServer.llmSecrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "conductor-server.conductorServer.llmSecretName" . }}
  labels:
    {{- include "conductor-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: conductor-server
  {{- include "conductor-server.annotations" . | nindent 2 }}
type: Opaque
data:
  {{- range $key, $value := .Values.conductorServer.llmSecrets.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
---
{{- end }}
{{- if .Values.maestroServer.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "conductor-server.maestroServer.secretName" . }}
  labels:
    {{- include "conductor-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: maestro-server
  {{- include "conductor-server.annotations" . | nindent 2 }}
type: Opaque
data:
  {{- range $key, $value := .Values.maestroServer.secrets.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
---
{{- end }}
{{- if .Values.maestroServer.llmSecrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "conductor-server.maestroServer.llmSecretName" . }}
  labels:
    {{- include "conductor-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: maestro-server
  {{- include "conductor-server.annotations" . | nindent 2 }}
type: Opaque
data:
  {{- range $key, $value := .Values.maestroServer.llmSecrets.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
