{{- if and .Values.mcpGateway.enabled .Values.mcpGateway.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "conductor-server.mcpGateway.serviceAccountName" . }}
  labels:
    {{- include "conductor-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp-gateway
  {{- with .Values.mcpGateway.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- if and .Values.conductorServer.enabled .Values.conductorServer.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "conductor-server.conductorServer.serviceAccountName" . }}
  labels:
    {{- include "conductor-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: conductor-server
  {{- with .Values.conductorServer.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- if and .Values.maestroServer.enabled .Values.maestroServer.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "conductor-server.maestroServer.serviceAccountName" . }}
  labels:
    {{- include "conductor-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: maestro-server
  {{- with .Values.maestroServer.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
