# Default values for lgtm-mcp
# This is a YAML-formatted file.

# Loki MCP Server configuration
loki:
  enabled: true

  # Image configuration
  image:
    repository: public.ecr.aws/cardinalhq.io/loki-mcp
    tag: ""
    pullPolicy: IfNotPresent

  # Image pull secrets for private registries
  imagePullSecrets: []

  # Service configuration
  service:
    type: ClusterIP
    port: 8080

  # Loki server URL (REQUIRED)
  # Note: All loki configuration (url and tenants) is stored in a Kubernetes Secret
  # and injected into the pod via envFrom for enhanced security
  url: ""

  # Tenant configuration
  # Structure: map of tenant names to HTTP headers
  # For single-tenant Loki (auth_enabled: false), use a single tenant with empty headers
  # For multi-tenant Loki (auth_enabled: true), configure multiple tenants with X-Scope-OrgID
  #
  # Examples:
  #
  # Single tenant (no auth_enabled):
  #   tenants:
  #     default: {}
  #
  # Single tenant (with auth_enabled):
  #   tenants:
  #     my-org:
  #       X-Scope-OrgID: "my-org"
  #
  # Multi-tenant:
  #   tenants:
  #     prod:
  #       X-Scope-OrgID: "prod"
  #     staging:
  #       X-Scope-OrgID: "staging"
  #       Authorization: "Bearer token123"
  #
  tenants:
    default: {}

  # Resource limits and requests
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

# Tempo MCP Server configuration
tempo:
  enabled: true

  # Image configuration
  image:
    repository: public.ecr.aws/cardinalhq.io/tempo-mcp
    tag: ""
    pullPolicy: IfNotPresent

  # Image pull secrets for private registries
  imagePullSecrets: []

  # Service configuration
  service:
    type: ClusterIP
    port: 8080

  # Tempo server URL (REQUIRED)
  # Note: All tempo configuration (url and headers) is stored in a Kubernetes Secret
  # and injected into the pod via envFrom for enhanced security
  url: ""

  # Optional HTTP headers to send with Tempo requests
  # Headers are stored as TEMPO_HEADER_<KEY> in the tempo-config secret
  # Header names are converted to uppercase with hyphens replaced by underscores
  # Example:
  #   headers:
  #     X-Scope-OrgID: "prod"                   # Becomes TEMPO_HEADER_X_SCOPE_ORGID
  headers: {}

  # Resource limits and requests
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

# CardinalHQ configuration (shared across all services)
cardinal:
  # REQUIRED: CardinalHQ API key for fetching OpenAI and Anthropic keys
  apiKey: ""
  secret:
    name: cardinal-api-key
    create: true

# Lakerunner configuration (optional, for loki)
lakerunner:
  # Lakerunner API host for query validation (optional)
  apiHost: ""
